
export const downloading = 'downloading'
export const referencePickerToggle = 'reference-picker-toggle'
export const referencePickerBookButton = 'reference-picker-book'
export const referencePickerChapterButtons = 'reference-picker-chapter'
export const referencePickerBackButton = 'reference-picker-back'

export const translationSelector = 'translation-selector'
export const translationSelectorItem = 'translation-selector-item'
export const searchInput = 'search-input'
export const clearSearchButton = 'clear-search-button'
export const foundPassages = 'found-passages'
export const foundPassage = 'found-passage'
export const chapterCaption = 'chapter-caption'
export const nextChapterButton = 'next-chapter-button'
export const previousChapterButton = 'previous-chapter-button'
export const copySelectedButton = 'copy-selected-button'
export const copySelectedOption = 'copy-selected-option'
export const copyFoundButton = 'copy-found-button'
export const copyFoundOption = 'copy-found-option'
export const copyTextarea = 'copy-textarea'
export const layoutToggle = 'layout-toggle'
export const passages = 'passages'
export const chapterContent = 'chapter-content'
export const chapterVerse = 'chapter-verse'
export const formattedVerse = 'formatted-verse'
export const nothingFound = 'nothing-found'
export const pageBackButton = 'page-back-button'

// Settings page left sidebar
export const settingsPageGeneral = 'settings-page-general'
export const settingsPageAppearance = 'settings-page-appearance'
export const settingsPageHighlights = 'settings-page-highlights'
export const settingsPageTranslations = 'settings-page-translations'
export const settingsPageBookNames = 'settings-page-book-names'
export const settingsPageFormatTemplates = 'settings-page-format-templates'
export const settingsPageCopyTemplates = 'settings-page-copy-templates'
export const settingsPageImportExport = 'settings-page-import-export'

export const settingsPanelBack = 'settings-panel-back'
export const settingsPanelTitle = 'settings-panel-title'
export const settingsLocaleSelector = 'settings-locale-selector'
export const settingsLocaleFilter = 'settings-locale-filter'
export const settingsLayoutToggle = 'settings-layout-toggle'
export const settingsReferencePickerOnStart = 'settings-reference-picker-on-start'

export const settingsScreenMode = 'settings-screen-mode'
export const settingsFontSize = 'settings-font-size'
export const settingsFontSizeIncrease = 'settings-font-size-increase'
export const settingsFontSizeDecrease = 'settings-font-size-decrease'

// Settings book names
export const settingsBookNamingInApp = 'settings-book-naming-in-app'
export const settingsBookNamingItem = 'settings-book-naming-item'
export const settingsBookNamingItemName = 'settings-book-naming-item-name'
export const settingsBookNamingItemBooks = 'settings-book-naming-item-books'
export const settingsBookNamingItemEditName = 'settings-book-naming-item-edit-name'
export const settingsBookNamingItemEditBooks = 'settings-book-naming-item-edit-books'
export const settingsBookNamingItemEditButton = 'settings-book-naming-item-edit-button'
export const settingsBookNamingItemRemoveButton = 'settings-book-naming-item-remove-button'
export const settingsBookNamingItemSaveButton = 'settings-book-naming-item-save-button'
export const settingsBookNamingItemCancelButton = 'settings-book-naming-item-cancel-button'
export const settingsBookNamingItemUseButton = 'settings-book-naming-item-use-button'
export const settingsBookNamingAddName = 'settings-book-naming-add-name'
export const settingsBookNamingAddBookNames = 'settings-book-naming-add-book-names'
export const settingsBookNamingAddButton = 'settings-book-naming-add-button'

// Settings copy templates
export const settingsCopyTemplatesDefault = 'settings-copy-templates-default'
export const settingsCopyTemplatesItemName = 'settings-copy-templates-item-name'
export const settingsCopyTemplatesEdit = 'settings-copy-templates-edit'
export const settingsCopyTemplatesName = 'settings-copy-templates-name'
export const settingsCopyTemplatesFormat = 'settings-copy-templates-format'
export const settingsCopyTemplatesBookNaming = 'settings-copy-templates-book-naming'
export const settingsCopyTemplatesSave = 'settings-copy-templates-save'
export const settingsCopyTemplatesCancel = 'settings-copy-templates-cancel'
export const settingsCopyTemplatesRemove = 'settings-copy-templates-remove'
export const settingsCopyTemplatesUseButton = 'settings-copy-templates-use-button'

export const settingsCopyTemplatesAddName = 'settings-copy-templates-add-name'
export const settingsCopyTemplatesAddFormat = 'settings-copy-templates-add-format'
export const settingsCopyTemplatesAddBookNaming = 'settings-copy-templates-add-book-naming'
export const settingsCopyTemplatesAdd = 'settings-copy-templates-add'

// Settings format templates
export const settingsFormatTemplateAppScreen = 'settings-format-templates-app-screen'
export const settingsFormatTemplatesItemName = 'settings-format-templates-item-name'
export const settingsFormatTemplatesAdd = 'settings-format-templates-add'
export const settingsFormatTemplateName = 'settings-format-templates-name'
export const settingsFormatTemplateRefPositionBefore = 'settings-format-templates-reference-position-before'
export const settingsFormatTemplateRefPositionAfter = 'settings-format-templates-reference-position-after'
export const settingsFormatTemplateRefPositionSameLine = 'settings-format-templates-reference-position-same-line'
export const settingsFormatTemplateRefPositionNewLine = 'settings-format-templates-reference-position-new-line'
export const settingsFormatTemplateTranslationAbbreviationNone = 'settings-format-templates-translation-abbreviation-none'
export const settingsFormatTemplateTranslationAbbreviationLowercase = 'settings-format-templates-translation-abbreviation-lowercase'
export const settingsFormatTemplateTranslationAbbreviationUppercase = 'settings-format-templates-translation-abbreviation-uppercase'
export const settingsFormatTemplateWithNumbers = 'settings-format-templates-with-numbers'
export const settingsFormatTemplateVerseNewLine = 'settings-format-templates-verse-new-line'
export const settingsFormatTemplateSeparatorChar = 'settings-format-templates-separator-char'
export const settingsFormatTemplateRangeChar = 'settings-format-templates-range-char'
export const settingsFormatTemplateReferenceCharsBefore = 'settings-format-templates-reference-chars-before'
export const settingsFormatTemplateReferenceCharsAfter = 'settings-format-templates-reference-chars-after'
export const settingsFormatTemplateQuoteCharsBefore = 'settings-format-templates-quote-chars-before'
export const settingsFormatTemplateQuoteCharsAfter = 'settings-format-templates-quote-chars-after'
export const settingsFormatTemplateNumberCharsBefore = 'settings-format-templates-number-chars-before'
export const settingsFormatTemplateNumberCharsAfter = 'settings-format-templates-number-chars-after'
// ... skip some properties
export const settingsFormatTemplateSave = 'settings-format-templates-save'
export const settingsFormatTemplateCancel = 'settings-format-templates-cancel'
export const settingsFormatTemplateRemove = 'settings-format-templates-remove'

// Settings translations
export const settingsTranslations = 'settings-translations'
export const settingsTranslationGroup = 'settings-translation-group'
export const settingsTranslationGroupHeader = 'settings-translation-group-header'
export const settingsTranslationGroupToggle = 'settings-translation-group-toggle'
export const settingsTranslationItem = 'settings-translation-item'
export const settingsTranslationItemToggle = 'settings-translation-item-toggle'
export const settingsTranslationDefault = 'settings-translation-default'
export const settingsTranslationGroupFlag = 'settings-translation-group-flag'
export const settingsTranslationGroupSelected = 'settings-translation-group-selected'
export const settingsTranslationsAllSelected = 'settings-translations-all-selected'
export const settingsTranslationsLocale = 'settings-translations-locale'
